# Generated by Django 6.0.4 on 2026-04-11 07:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtor',
            options={'ordering': ['-updated_at', 'name'], 'verbose_name': 'Pelanggan Piutang', 'verbose_name_plural': 'Daftar Pelanggan Piutang'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Entri Transaksi', 'verbose_name_plural': 'Riwayat Transaksi'},
        ),
        migrations.AlterField(
            model_name='debtor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pendaftaran'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='name',
            field=models.CharField(help_text='Gunakan nama asli pelanggan untuk akurasi data.', max_length=255, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nama yang sering dipanggil di lingkungan warung.', max_length=255, null=True, verbose_name='Nama Panggilan'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Nomor telepon harus dalam format: '08123456789'. Maksimal 15 digit.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Nomor WhatsApp/HP'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Disarankan upload foto agar memudahkan identifikasi wajah.', null=True, upload_to='debtor_photos/', verbose_name='Foto Profil'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total akumulasi piutang yang belum dibayarkan.', max_digits=15, verbose_name='Saldo Utang Terkini'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Log Perubahan Terakhir'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='user',
            field=models.ForeignKey(help_text='Akun pemilik warung yang mengelola data ini.', on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to=settings.AUTH_USER_MODEL, verbose_name='Petugas Management'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Masukkan jumlah uang tanpa titik atau koma.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Nominal Transaksi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='debt_management.debtor', verbose_name='Pelanggan Terkait'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, help_text="Contoh: 'Beli semen 2 sak' atau 'Sisa kembalian'", null=True, verbose_name='Catatan Tambahan'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Transaksi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEBT', 'Penambahan Utang'), ('PAYMENT', 'Pembayaran Cicilan')], max_length=15, verbose_name='Jenis Transaksi'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['name'], name='debt_manage_name_0cca64_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['user'], name='debt_manage_user_id_6512ed_idx'),
        ),
    ]
